
name: Pokemon Test And Deploy Contentful

on:
  pull_request:
    branches: [ master ]
    paths:
      - "packages/pokemon/**"
      - ".github/workflows/pokemon-pr.yml"
  push:
    branches: [ master ]
    paths:
      - "packages/pokemon/**"
      - ".github/workflows/pokemon-pr.yml"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Uses Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - run: npm install -g yarn@1

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
        
      - name: yarn install, and test
        run: |
          yarn
          yarn test
        env:
          CI: true
  deploy_contentful:
    name: Deploy Contentful Sandbox
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Uses Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - run: npm install -g yarn@1

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
        
      - name: yarn install
        run: |
          yarn

      - name: Deploy Contentful
        uses: contentful/contentful-action@main
        env:
          SPACE_ID: ${{ secrets.POKEMON_CONTENTFUL_SPACE_ID }}
          MANAGEMENT_API_KEY: ${{ secrets.POKEMON_CONTENTFUL_MANAGEMENT_API_KEY }}
          MIGRATIONS_DIR: 'packages/pokemon/contentful-migrations/src'
